<!ELEMENT Events (Event*)>
<!ELEMENT Event (Title, Category+, EventType, Venue, Address, City,
Country, GeoLocation?, StartDateTime, EndDateTime, Capacity,
TicketTypes, Bookings, Organizer, Status, Description, Media?)>
<!ATTLIST Event EventID CDATA #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Category (#PCDATA)>
<!ELEMENT EventType (#PCDATA)>
<!ELEMENT Venue (#PCDATA)>

<!ELEMENT Address (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT GeoLocation EMPTY>
<!ATTLIST GeoLocation Latitude CDATA #REQUIRED Longitude CDATA #REQUIRED>
<!ELEMENT StartDateTime (#PCDATA)>
<!ELEMENT EndDateTime (#PCDATA)>
<!ELEMENT Capacity (#PCDATA)>
<!ELEMENT TicketTypes (TicketType+)>
<!ELEMENT TicketType (Name, Price, Quantity, Available)>
<!ATTLIST TicketType TicketTypeID CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Available (#PCDATA)>
<!ELEMENT Bookings (Booking*)>
<!ELEMENT Booking (Attendee, Time, TicketTypeRef, NumberOfTickets,
TotalCost, BookingStatus)>
<!ATTLIST Booking BookingID CDATA #REQUIRED>
<!ELEMENT Attendee EMPTY>
<!ATTLIST Attendee UserID CDATA #REQUIRED>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT TicketTypeRef (#PCDATA)>
<!ELEMENT NumberOfTickets (#PCDATA)>
<!ELEMENT TotalCost (#PCDATA)>
<!ELEMENT BookingStatus (#PCDATA)>
<!ELEMENT Organizer EMPTY>
<!ATTLIST Organizer UserID CDATA #REQUIRED>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Media (Photo*)>
<!ELEMENT Photo (#PCDATA)>